pipeline {
    agent any
    tools {
        maven 'LocalMaven'
    }
    stages {
        stage('MavenHome') {
            steps {
                echo "Hello World!!"
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'   
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
