pipeline {
    agent any
    stages {
        stage('MavenHome') {
            steps {
                echo "Hello World!!"
            }
        }
        stage('Build') {
            steps {
                withMaven(maven : 'maven_3_6_0') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                withMaven(maven : 'maven_3_6_0') {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}
